name: Push component to ESP Component Registry

on:
  push:
    branches:
      - main
    paths:
      - "idf_component.yml"

jobs:
  upload_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the registry
        uses: espressif/upload-components-ci-action@v2
        with:
          namespace: "lutzbellmann"
          components: "esp32_aht20_bmp280:."
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
